setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS PUSHD_SILENT
setopt INTERACTIVE_COMMENTS NO_BEEP NO_FLOW_CONTROL
setopt EXTENDED_GLOB GLOB_DOTS NUMERIC_GLOB_SORT
setopt PROMPT_SUBST

# Keep history private, useful, and shared between concurrent shells.
HISTFILE="$AWESOME_ZSH_STATE/history"
HISTSIZE=100000
SAVEHIST=100000
setopt APPEND_HISTORY EXTENDED_HISTORY INC_APPEND_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST HIST_FIND_NO_DUPS HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE HIST_REDUCE_BLANKS HIST_SAVE_NO_DUPS SHARE_HISTORY

